# Generated by Django 5.2.17 on 2026-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_compatibilityrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_external_id', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
