import React,{useEffect,useState} from 'react';
import {App,Avatar,Breadcrumb,Button,Card,Form,Input,Modal,Select,Space,Switch,Table,Tag,Typography,Upload} from 'antd';
import {PlusOutlined,UploadOutlined,SearchOutlined} from '@ant-design/icons';
const {Title,Text}=Typography;
const api=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api';
async function request(path,options={}){
 const response=await fetch(api+path,{credentials:'include',...options});
 const data=await response.json();
 if(!response.ok)throw new Error(data.message||'Không thể lưu dữ liệu.');
 return data;
}
export function EmployeeManagement(){
 const {message}=App.useApp();
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const [form]=Form.useForm();
 useEffect(()=>{request('/admin/employees/').then(data=>setItems(data.results)).catch(e=>message.error(e.message)).finally(()=>setLoading(false))},[message]);
 const save=async values=>{setSaving(true);try{const data=await request('/admin/employees/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});setItems(current=>[data.employee,...current]);setOpen(false);form.resetFields();message.success('Đã thêm nhân viên.')}catch(e){message.error(e.message)}finally{setSaving(false)}};
 const toggle=async(item,active)=>{setSaving(true);try{const data=await request(`/admin/employees/${item.id}/`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active})});setItems(current=>current.map(row=>row.id===item.id?data.employee:row))}catch(e){message.error(e.message)}finally{setSaving(false)}};
 const columns=[{title:'NHÂN VIÊN',dataIndex:'full_name',width:340,render:(name,item)=><div className="employee-identity"><Avatar>{name[0]}</Avatar><div className="employee-identity-text"><Text strong>{name}</Text><Text type="secondary">{item.email}</Text></div></div>},{title:'SỐ ĐIỆN THOẠI',dataIndex:'phone',width:170},{title:'CHỨC VỤ',dataIndex:'role_label',width:190,render:value=><Tag color="blue">{value}</Tag>},{title:'TRẠNG THÁI',dataIndex:'active',width:190,render:(active,item)=><Switch checked={active} disabled={saving} checkedChildren="Đang làm việc" unCheckedChildren="Ngừng làm việc" onChange={value=>toggle(item,value)}/>},{title:'NGÀY THÊM',dataIndex:'created_at',width:210,render:value=>new Date(value).toLocaleString('vi-VN')}];
 return <><Breadcrumb items={[{title:'Quản lý nhân viên'}]}/><div className="content-title"><div><Title level={2}>Quản lý nhân viên</Title><Text type="secondary">Danh sách nhân viên để phân công xử lý đơn hàng.</Text></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>Thêm nhân viên</Button></div><Card className="catalog-card"><Input prefix={<SearchOutlined/>} placeholder="Tìm tên, email, số điện thoại" value={query} onChange={e=>setQuery(e.target.value)} style={{maxWidth:400,marginBottom:20}}/><Table className="employee-table" tableLayout="fixed" rowKey="id" loading={loading} columns={columns} dataSource={items.filter(item=>`${item.full_name} ${item.email} ${item.phone}`.toLowerCase().includes(query.toLowerCase()))} pagination={{pageSize:8}} scroll={{x:1100}}/></Card><Modal title="Thêm nhân viên" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} confirmLoading={saving} okText="Lưu" cancelText="Hủy"><Form form={form} layout="vertical" onFinish={save} initialValues={{role:'ORDER_PROCESSOR'}}><Form.Item name="full_name" label="Họ tên" rules={[{required:true,whitespace:true,message:'Nhập họ tên'}]}><Input maxLength={150}/></Form.Item><Form.Item name="email" label="Email" rules={[{required:true,type:'email',message:'Nhập email hợp lệ'}]}><Input/></Form.Item><Form.Item name="phone" label="Số điện thoại" rules={[{required:true,pattern:/^0\d{9}$/,message:'Nhập số điện thoại gồm 10 chữ số'}]}><Input maxLength={10}/></Form.Item><Form.Item name="role" label="Chức vụ" rules={[{required:true,message:'Chọn chức vụ'}]}><Select options={[{value:'WAREHOUSE',label:'Nhân viên kho'},{value:'ORDER_PROCESSOR',label:'Nhân viên xử lý'}]}/></Form.Item></Form></Modal></>;
}
export function DataManagement(){
 const {message}=App.useApp();
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[preview,setPreview]=useState(null),[reading,setReading]=useState(false);
 useEffect(()=>{request('/admin/documents/').then(data=>setItems(data.results)).catch(e=>message.error(e.message)).finally(()=>setLoading(false))},[message]);
 const upload=async file=>{if(file.size>5*1024*1024){message.error('Dung lượng tối đa 5 MB mỗi file.');return false}setUploading(true);try{const body=new FormData();body.append('file',file);const data=await request('/admin/documents/',{method:'POST',body});setItems(current=>[data.document,...current]);message.success('Đã import và trích xuất văn bản.')}catch(e){message.error(e.message)}finally{setUploading(false)}return false};
 const view=async item=>{setReading(true);try{const data=await request(`/admin/documents/${item.id}/`);setPreview(data.document)}catch(e){message.error(e.message)}finally{setReading(false)}};
 return <><Breadcrumb items={[{title:'Quản lý dữ liệu'}]}/><div className="content-title"><div><Title level={2}>Quản lý dữ liệu</Title><Text type="secondary">Import tài liệu làm nguồn dữ liệu cho AI.</Text></div><Upload accept=".md,.csv,.pdf,.docx" showUploadList={false} beforeUpload={upload} disabled={uploading}><Button type="primary" icon={<UploadOutlined/>} loading={uploading}>Import tài liệu</Button></Upload></div><Card className="catalog-card"><p>Markdown (.md), CSV, PDF có văn bản, Word (.docx) · Tối đa 5 MB/file. PDF scan cần chuyển thành văn bản trước khi import.</p><Table rowKey="id" loading={loading} dataSource={items} scroll={{x:750}} columns={[{title:'TÊN FILE',dataIndex:'name'},{title:'DUNG LƯỢNG',dataIndex:'size',render:value=>`${(value/1024).toFixed(1)} KB`},{title:'TRẠNG THÁI',render:()=> <Tag color="success">Đã trích xuất văn bản</Tag>},{title:'NGÀY IMPORT',dataIndex:'created_at',render:value=>new Date(value).toLocaleString('vi-VN')},{title:'',render:(_,item)=><Button disabled={reading} onClick={()=>view(item)}>Xem nội dung</Button>}]} pagination={{pageSize:8}}/></Card><Modal title={preview?.name} open={!!preview} onCancel={()=>setPreview(null)} footer={null} width={800}><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:'65vh',overflow:'auto'}}>{preview?.text}</pre></Modal></>;
}
