import React,{useEffect,useState} from 'react';
import {App,Breadcrumb,Button,Card,Form,Input,Modal,Select,Space,Switch,Table,Typography} from 'antd';
const api=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api';
const operators=[{value:'equal',label:'Bằng nhau'},{value:'overlap',label:'Có giá trị chung'},{value:'gte',label:'Lớn hơn hoặc bằng (≥)'},{value:'lte',label:'Nhỏ hơn hoặc bằng (≤)'}];
export default function CompatibilityManagement({categories,definitions,products}){
 const {message,modal}=App.useApp();
 const [rules,setRules]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editing,setEditing]=useState(null),[open,setOpen]=useState(false);
 const [form]=Form.useForm();
 const source=Form.useWatch('source_category',form),target=Form.useWatch('target_category',form);
 const request=async(path='',options={})=>{const response=await fetch(`${api}/compatibility-rules/${path}`,{credentials:'include',...options});const data=await response.json();if(!response.ok)throw new Error(data.message);return data};
 useEffect(()=>{request().then(data=>setRules(data.results)).catch(()=>message.error('Không thể tải ràng buộc.')).finally(()=>setLoading(false))},[message]);
 const attributes=category=>[...new Set([...definitions.map(item=>item.name),...products.filter(p=>p.cat===category).flatMap(p=>(p.attributes||[]).map(a=>a.name))])].map(name=>({value:name,label:name}));
 const save=async(values,rule=editing)=>{setSaving(true);try{const data=await request(rule?`${rule.id}/`:'',{method:rule?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});setRules(current=>rule?current.map(item=>item.id===rule.id?data.rule:item):[...current,data.rule]);setOpen(false);message.success('Đã lưu ràng buộc.')}catch(e){message.error(e.message||'Không thể lưu ràng buộc.')}finally{setSaving(false)}};
 const edit=rule=>{setEditing(rule);form.resetFields();form.setFieldsValue(rule||{operator:'equal',active:true});setOpen(true)};
 const remove=rule=>modal.confirm({title:'Xóa ràng buộc?',content:rule.name,okText:'Xóa',cancelText:'Hủy',onOk:async()=>{try{await request(`${rule.id}/`,{method:'DELETE'});setRules(current=>current.filter(item=>item.id!==rule.id))}catch(e){message.error(e.message);throw e}}});
 const columns=[{title:'RÀNG BUỘC',dataIndex:'name',width:240},{title:'LINH KIỆN A',render:(_,r)=>`${r.source_category} · ${r.source_attribute}`,width:220},{title:'SO SÁNH',dataIndex:'operator',render:value=>operators.find(item=>item.value===value)?.label,width:200},{title:'LINH KIỆN B',render:(_,r)=>`${r.target_category} · ${r.target_attribute}`,width:220},{title:'ÁP DỤNG',dataIndex:'active',render:(value,r)=><Switch checked={value} disabled={saving} onChange={active=>save({active},r)}/>,width:110},{title:'',render:(_,r)=><Space><Button onClick={()=>edit(r)}>Sửa</Button><Button danger onClick={()=>remove(r)}>Xóa</Button></Space>,width:170}];
 return <><Breadcrumb items={[{title:'Quản lý sản phẩm'},{title:'Quản lý tương thích'}]}/><div className="content-title"><div><Typography.Title level={2}>Quản lý tương thích</Typography.Title><Typography.Text type="secondary">Ràng buộc thuộc tính giữa hai nhóm linh kiện khi build PC.</Typography.Text></div><Button type="primary" onClick={()=>edit(null)}>Thêm ràng buộc</Button></div><Card><p>Ví dụ: Socket CPU bằng Socket Mainboard; loại RAM có giá trị chung với RAM hỗ trợ của Mainboard. So sánh số yêu cầu cùng đơn vị.</p><Table className="compatibility-table" tableLayout="fixed" rowKey="id" columns={columns} dataSource={rules} loading={loading} scroll={{x:1160}}/></Card><Modal title={editing?'Sửa ràng buộc':'Thêm ràng buộc'} open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} confirmLoading={saving} okText="Lưu" cancelText="Hủy" width={640}><Form form={form} layout="vertical" onFinish={values=>save(values)}><Form.Item name="name" label="Tên ràng buộc" rules={[{required:true,whitespace:true}]}><Input maxLength={150}/></Form.Item>{[['source','Linh kiện A',source],['target','Linh kiện B',target]].map(([key,label,category])=><React.Fragment key={key}><Form.Item name={`${key}_category`} label={label} rules={[{required:true}]}><Select options={categories.map(name=>({value:name,label:name}))} onChange={()=>form.setFieldValue(`${key}_attribute`,undefined)}/></Form.Item><Form.Item name={`${key}_attribute`} label={`Thuộc tính ${label}`} rules={[{required:true}]}><Select showSearch options={attributes(category)} placeholder="Chọn thuộc tính sản phẩm"/></Form.Item></React.Fragment>)}<Form.Item name="operator" label="A so với B" rules={[{required:true}]}><Select options={operators}/></Form.Item><Form.Item name="active" label="Áp dụng" valuePropName="checked"><Switch/></Form.Item></Form></Modal></>;
}
