import React,{useEffect,useState} from 'react';
import {App,Breadcrumb,Button,Card,Form,Input,InputNumber,Modal,Select,Switch,Table,Tag,Typography} from 'antd';
const api=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api';
const local=value=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export default function FlashSaleManagement({products}){
 const {message}=App.useApp();const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[editing,setEditing]=useState(null);const [form]=Form.useForm();
 const request=async(path='',options={})=>{const response=await fetch(`${api}/admin/flash-sales/${path}`,{credentials:'include',...options});const data=await response.json();if(!response.ok)throw new Error(data.message);return data};
 useEffect(()=>{request().then(data=>setItems(data.results)).catch(e=>message.error(e.message)).finally(()=>setLoading(false))},[message]);
 const save=async(values,item=editing)=>{setSaving(true);try{const payload={...values};if(payload.starts_at)payload.starts_at=new Date(payload.starts_at).toISOString();if(payload.ends_at)payload.ends_at=new Date(payload.ends_at).toISOString();const data=await request(item?`${item.id}/`:'',{method:item?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setItems(current=>item?current.map(s=>s.id===item.id?data.sale:s):[data.sale,...current]);setOpen(false);message.success('Đã lưu Flash sale.')}catch(e){message.error(e.message)}finally{setSaving(false)}};
 const edit=item=>{setEditing(item);form.resetFields();form.setFieldsValue(item?{...item,starts_at:local(item.starts_at),ends_at:local(item.ends_at)}:{quantity:1,active:true});setOpen(true)};
 return <><Breadcrumb items={[{title:'Khuyến mãi'},{title:'Flash sale'}]}/><div className="content-title"><div><Typography.Title level={2}>Flash sale</Typography.Title><Typography.Text type="secondary">Chọn sản phẩm, hạn mức và lịch ưu đãi. Giá bán lấy từ sản phẩm.</Typography.Text></div><Button type="primary" onClick={()=>edit(null)}>Thêm Flash sale</Button></div><Card><Table className="flash-admin-table" rowKey="id" loading={loading} dataSource={items} scroll={{x:1100}} columns={[{title:'SẢN PHẨM',width:280,render:(_,s)=>s.product?.name||`Sản phẩm ${s.product_id} không còn tồn tại`},{title:'SỐ LƯỢNG',dataIndex:'quantity',width:100},{title:'ĐÃ BÁN',dataIndex:'sold',width:90},{title:'THỜI GIAN',width:260,render:(_,s)=><>{new Date(s.starts_at).toLocaleString('vi-VN')}<br/>→ {new Date(s.ends_at).toLocaleString('vi-VN')}</>},{title:'TRẠNG THÁI',width:150,render:(_,s)=><Tag>{!s.active?'Tạm tắt':Date.now()>=Date.parse(s.ends_at)?'Đã kết thúc':Date.now()<Date.parse(s.starts_at)?'Sắp diễn ra':s.remaining<=0?'Hết suất':'Đang diễn ra'}</Tag>},{title:'ÁP DỤNG',width:110,render:(_,s)=><Switch checked={s.active} disabled={saving} onChange={active=>save({active},s)}/>},{title:'',width:90,render:(_,s)=><Button onClick={()=>edit(s)}>Sửa</Button>} ]}/></Card><Modal title={editing?'Sửa Flash sale':'Thêm Flash sale'} open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} confirmLoading={saving} okText="Lưu" cancelText="Hủy"><Form form={form} layout="vertical" onFinish={values=>save(values)}><Form.Item name="product_id" label="Sản phẩm" rules={[{required:true}]}><Select showSearch optionFilterProp="label" disabled={!!editing?.sold} options={products.map(p=>({value:String(p.id),label:`${p.name} (${p.sku||p.id})`}))}/></Form.Item><Form.Item name="quantity" label="Số lượng Flash sale" rules={[{required:true,type:'number',min:1}]}><InputNumber min={Math.max(1,editing?.sold||0)} precision={0} style={{width:'100%'}}/></Form.Item><Form.Item name="starts_at" label="Bắt đầu" rules={[{required:true}]}><Input type="datetime-local"/></Form.Item><Form.Item name="ends_at" label="Kết thúc" rules={[{required:true}]}><Input type="datetime-local"/></Form.Item><Form.Item name="active" label="Áp dụng" valuePropName="checked"><Switch/></Form.Item></Form></Modal></>;
}
