import React,{useMemo,useState}from'react';
import{App as AntApp,Avatar,Badge,Breadcrumb,Button,Card,Col,ConfigProvider,Drawer,Dropdown,Form,Image,Input,InputNumber,Layout,Menu,Modal,Row,Select,Space,Statistic,Switch,Table,Tag,Tooltip,Typography,message}from'antd';
import{AppstoreOutlined,BellOutlined,DeleteOutlined,EditOutlined,EyeInvisibleOutlined,EyeOutlined,InboxOutlined,MenuFoldOutlined,MenuUnfoldOutlined,MoreOutlined,PlusOutlined,SaveOutlined,SearchOutlined,SettingOutlined,ShoppingCartOutlined,ShopOutlined,TagsOutlined,TeamOutlined,WarningOutlined}from'@ant-design/icons';
import'antd/dist/reset.css';
import'./admin.css';

const{Header,Sider,Content}=Layout,{Title,Text}=Typography;
const categories=['CPU','VGA','Mainboard','RAM','SSD','Nguồn','Case'];
const blank={name:'',sku:'',cat:'CPU',brand:'',price:null,old:null,stock:0,badge:'MỚI',img:'',active:true,featured:false,description:''};
const money=n=>Number(n||0).toLocaleString('vi-VN')+'₫';

export default function AdminApp(props){return <ConfigProvider theme={{token:{colorPrimary:'#1768f2',borderRadius:6,fontFamily:"'Be Vietnam Pro', sans-serif",colorBgLayout:'#f4f6f9'},components:{Layout:{headerBg:'#fff',siderBg:'#0b1525'},Table:{headerBg:'#fafbfc',headerColor:'#768196',rowHoverBg:'#f6f9ff'}}}}><AntApp><Admin seed={props.seed}/></AntApp></ConfigProvider>}

function Admin({seed}){
 const[collapsed,setCollapsed]=useState(false),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all');
 const[msg,context]=message.useMessage();
 const[items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem('techzone_products'))||seed.map((x,i)=>({...x,sku:`TZ-${x.cat.toUpperCase()}-${1001+i}`,stock:12+i*7,active:true,featured:i<4}))}catch{return seed}});
 const persist=next=>{setItems(next);localStorage.setItem('techzone_products',JSON.stringify(next));msg.success('Đã đồng bộ sang website consumer')};
 const filtered=useMemo(()=>items.filter(x=>(category==='all'||x.cat===category)&&(x.name.toLowerCase().includes(query.toLowerCase())||(x.sku||'').toLowerCase().includes(query.toLowerCase()))),[items,query,category]);
 const edit=p=>{setEditing(p);setFormOpen(true)};
 const save=v=>{const p={...editing,...v,id:editing?.id||Date.now(),price:Number(v.price),old:Number(v.old||v.price),stock:Number(v.stock||0),img:v.img||'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80',rate:editing?.rate||5,reviews:editing?.reviews||0};persist(editing?.id?items.map(x=>x.id===editing.id?p:x):[p,...items]);setFormOpen(false);setEditing(null)};
 const remove=p=>Modal.confirm({title:'Xóa sản phẩm?',content:`“${p.name}” sẽ bị xóa khỏi catalog.`,okText:'Xóa',cancelText:'Hủy',okButtonProps:{danger:true},onOk:()=>persist(items.filter(x=>x.id!==p.id))});
 const toggle=(p,key,value)=>persist(items.map(x=>x.id===p.id?{...x,[key]:value}:x));
 const columns=[
  {title:'SẢN PHẨM',dataIndex:'name',width:340,render:(_,p)=><Space size={12}><Image width={48} height={48} style={{objectFit:'cover',borderRadius:6}} src={p.img} fallback="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="/><Space direction="vertical" size={1}><Text strong>{p.name}</Text><Text type="secondary" className="sku">{p.sku||'Chưa có SKU'}</Text></Space></Space>},
  {title:'DANH MỤC',dataIndex:'cat',width:120,render:v=><Tag bordered={false}>{v}</Tag>},
  {title:'GIÁ BÁN',dataIndex:'price',width:145,render:(v,p)=><Space direction="vertical" size={0}><Text strong>{money(v)}</Text>{p.old>v&&<Text delete type="secondary" className="sku">{money(p.old)}</Text>}</Space>},
  {title:'TỒN KHO',dataIndex:'stock',width:120,sorter:(a,b)=>a.stock-b.stock,render:v=><Badge status={v===0?'error':v<10?'warning':'success'} text={`${v||0} sản phẩm`}/>},
  {title:'TRẠNG THÁI',dataIndex:'active',width:130,filters:[{text:'Đang bán',value:true},{text:'Đang ẩn',value:false}],onFilter:(v,r)=>r.active===v,render:(v,p)=><Button type="text" size="small" icon={v?<EyeOutlined/>:<EyeInvisibleOutlined/>} className={v?'selling':'hidden'} onClick={()=>toggle(p,'active',!v)}>{v?'Đang bán':'Đang ẩn'}</Button>},
  {title:'NỔI BẬT',dataIndex:'featured',width:90,align:'center',render:(v,p)=><Switch size="small" checked={v} onChange={n=>toggle(p,'featured',n)}/>},
  {title:'',key:'action',width:62,fixed:'right',render:(_,p)=><Dropdown trigger={['click']} menu={{items:[{key:'edit',icon:<EditOutlined/>,label:'Chỉnh sửa',onClick:()=>edit(p)},{type:'divider'},{key:'delete',danger:true,icon:<DeleteOutlined/>,label:'Xóa sản phẩm',onClick:()=>remove(p)}]}}><Button type="text" icon={<MoreOutlined/>}/></Dropdown>}
 ];
 const menu=[{key:'overview',icon:<AppstoreOutlined/>,label:'Tổng quan'},{key:'products',icon:<ShopOutlined/>,label:'Sản phẩm'},{key:'inventory',icon:<InboxOutlined/>,label:'Kho hàng'},{key:'promotions',icon:<TagsOutlined/>,label:'Khuyến mãi'},{key:'orders',icon:<ShoppingCartOutlined/>,label:'Đơn hàng'},{type:'divider'},{key:'customers',icon:<TeamOutlined/>,label:'Khách hàng'},{key:'settings',icon:<SettingOutlined/>,label:'Cài đặt'}];
 return <Layout className="ant-admin-layout">{context}<Sider collapsible collapsed={collapsed} trigger={null} width={238} className="ant-admin-sider"><a className="ant-brand" href="/"><span>TZ</span>{!collapsed&&<b>TECHZONE<small>ADMIN CENTER</small></b>}</a>{!collapsed&&<div className="store-select"><Text>KHÔNG GIAN LÀM VIỆC</Text><b>TechZone Store</b></div>}<Menu theme="dark" mode="inline" selectedKeys={['products']} items={menu}/><div className="sider-user"><Avatar style={{background:'#254366'}}>HV</Avatar>{!collapsed&&<><span><b>Hữu Vy</b><small>Quản trị viên</small></span><MoreOutlined/></>}</div></Sider>
  <Layout><Header className="ant-admin-header"><Button type="text" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(!collapsed)}/><Input variant="borderless" prefix={<SearchOutlined/>} placeholder="Tìm nhanh sản phẩm, đơn hàng..." className="header-search"/><Space className="header-right"><Button type="link" href="/" target="_blank">Xem cửa hàng <ArrowUpRight/></Button><Badge dot><Button type="text" shape="circle" icon={<BellOutlined/>}/></Badge></Space></Header>
   <Content className="ant-admin-content"><Breadcrumb items={[{title:'Catalog'},{title:'Sản phẩm'}]}/><div className="content-title"><div><Title level={2}>Quản lý sản phẩm</Title><Text type="secondary">Quản lý thông tin, giá bán và trạng thái sản phẩm trên cửa hàng.</Text></div><Button type="primary" icon={<PlusOutlined/>} size="large" onClick={()=>{setEditing(null);setFormOpen(true)}}>Thêm sản phẩm</Button></div>
    <Row gutter={[14,14]} className="stat-row"><Stat title="Tổng sản phẩm" value={items.length} icon={<ShopOutlined/>}/><Stat title="Đang hiển thị" value={items.filter(x=>x.active).length} icon={<EyeOutlined/>} color="green"/><Stat title="Sắp hết hàng" value={items.filter(x=>x.stock>0&&x.stock<10).length} icon={<WarningOutlined/>} color="orange"/><Stat title="Hết hàng" value={items.filter(x=>!x.stock).length} icon={<InboxOutlined/>} color="red"/></Row>
    <Card className="catalog-card" styles={{body:{padding:0}}}><div className="catalog-tools"><Input allowClear prefix={<SearchOutlined/>} placeholder="Tìm theo tên hoặc mã SKU..." value={query} onChange={e=>setQuery(e.target.value)} className="catalog-search"/><Select value={category} onChange={setCategory} options={[{label:'Tất cả danh mục',value:'all'},...categories.map(x=>({label:x,value:x}))]}/><Text type="secondary">{filtered.length} sản phẩm</Text></div><Table rowKey="id" columns={columns} dataSource={filtered} scroll={{x:1050}} pagination={{pageSize:8,showSizeChanger:false,showTotal:n=>`Tổng ${n} sản phẩm`}}/></Card>
   </Content></Layout><ProductDrawer open={formOpen} data={editing} close={()=>{setFormOpen(false);setEditing(null)}} save={save}/></Layout>
}
function Stat({title,value,icon,color=''}){return <Col xs={12} lg={6}><Card className="stat-card"><Space><Avatar size={46} className={`stat-icon ${color}`} icon={icon}/><Statistic title={title} value={value}/></Space></Card></Col>}
function ProductDrawer({open,data,close,save}){const[form]=Form.useForm();return <Drawer title={<Space direction="vertical" size={0}><Text type="secondary" className="drawer-eyebrow">{data?'CHỈNH SỬA':'TẠO MỚI'}</Text><Title level={4} style={{margin:0}}>{data?'Cập nhật sản phẩm':'Thêm sản phẩm'}</Title></Space>} width={540} open={open} onClose={close} destroyOnHidden afterOpenChange={v=>v&&form.setFieldsValue(data||blank)} extra={<Button type="primary" icon={<SaveOutlined/>} onClick={()=>form.submit()}>Lưu</Button>}><Form form={form} layout="vertical" onFinish={save} initialValues={blank}><Form.Item label="Tên sản phẩm" name="name" rules={[{required:true,message:'Nhập tên sản phẩm'}]}><Input placeholder="AMD Ryzen 7 7800X3D"/></Form.Item><Row gutter={12}><Col span={12}><Form.Item label="Mã SKU" name="sku" rules={[{required:true,message:'Nhập mã SKU'}]}><Input placeholder="TZ-CPU-1001"/></Form.Item></Col><Col span={12}><Form.Item label="Thương hiệu" name="brand"><Input placeholder="AMD"/></Form.Item></Col></Row><Row gutter={12}><Col span={12}><Form.Item label="Danh mục" name="cat"><Select options={categories.map(x=>({label:x,value:x}))}/></Form.Item></Col><Col span={12}><Form.Item label="Nhãn sản phẩm" name="badge"><Input placeholder="MỚI"/></Form.Item></Col></Row><Row gutter={12}><Col span={12}><Form.Item label="Giá bán" name="price" rules={[{required:true,message:'Nhập giá bán'}]}><InputNumber min={0} style={{width:'100%'}} addonAfter="₫"/></Form.Item></Col><Col span={12}><Form.Item label="Giá gốc" name="old"><InputNumber min={0} style={{width:'100%'}} addonAfter="₫"/></Form.Item></Col></Row><Form.Item label="Số lượng tồn kho" name="stock"><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item label="URL hình ảnh" name="img"><Input placeholder="https://..."/></Form.Item><Form.Item label="Mô tả" name="description"><Input.TextArea rows={4} placeholder="Thông tin nổi bật của sản phẩm..."/></Form.Item><Card size="small"><Form.Item name="active" valuePropName="checked" label="Hiển thị trên cửa hàng"><Switch checkedChildren="Đang bán" unCheckedChildren="Đang ẩn"/></Form.Item><Form.Item name="featured" valuePropName="checked" label="Sản phẩm nổi bật" style={{marginBottom:0}}><Switch/></Form.Item></Card></Form></Drawer>}
function ArrowUpRight(){return <span style={{fontSize:12}}>↗</span>}
