import AdminOverview from './AdminOverview.jsx';
import CompatibilityManagement from './CompatibilityManagement.jsx';
import {EmployeeManagement,DataManagement} from './AdminManagement.jsx';
import React,{useEffect,useMemo,useState}from'react';
import{App as AntApp,Avatar,Badge,Breadcrumb,Button,Card,Col,ConfigProvider,Drawer,Dropdown,Form,Image,Input,InputNumber,Layout,List,Menu,Modal,Row,Select,Space,Statistic,Switch,Table,Tag,Tooltip,Typography,message}from'antd';
import{AppstoreOutlined,BellOutlined,DeleteOutlined,EditOutlined,EyeInvisibleOutlined,EyeOutlined,InboxOutlined,MenuFoldOutlined,MenuUnfoldOutlined,MoreOutlined,PlusOutlined,SaveOutlined,SearchOutlined,SettingOutlined,ShoppingCartOutlined,ShopOutlined,TagsOutlined,TeamOutlined,WarningOutlined}from'@ant-design/icons';
import'antd/dist/reset.css';
import viVN from'antd/locale/vi_VN';
import'./admin.css';

const{Header,Sider,Content}=Layout,{Title,Text}=Typography;
const defaultCategories=['CPU','VGA','Mainboard','RAM','SSD','Nguồn','Case'];
const blank={name:'',sku:'',cat:'CPU',brand:'',price:null,old:null,stock:0,badge:'MỚI',img:'',active:true,featured:false,description:'',productInfo:'',attributes:[{name:'',value:''}]};
const money=n=>Number(n||0).toLocaleString('vi-VN')+'₫';
const apiBaseUrl=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api';

export default function AdminApp(props){return <ConfigProvider locale={viVN} theme={{token:{colorPrimary:'#1768f2',borderRadius:6,fontFamily:"Roboto, Arial, sans-serif",colorBgLayout:'#f4f6f9'},components:{Layout:{headerBg:'#fff',siderBg:'#0b1525'},Table:{headerBg:'#fafbfc',headerColor:'#768196',rowHoverBg:'#f6f9ff'}}}}><AntApp><Admin seed={props.seed}/></AntApp></ConfigProvider>}

function Admin({seed}){
 const[collapsed,setCollapsed]=useState(false),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all');
 const[section,setSection]=useState('overview'),[customers,setCustomers]=useState([]),[loadingCustomers,setLoadingCustomers]=useState(false),[orders,setOrders]=useState([]),[loadingOrders,setLoadingOrders]=useState(false);
 const[categories,setCategories]=useState(()=>{try{return JSON.parse(localStorage.getItem('techzone_categories'))||defaultCategories}catch{return defaultCategories}});
 const[attributeDefinitions,setAttributeDefinitions]=useState(()=>{try{return (JSON.parse(localStorage.getItem('techzone_product_attributes'))||[]).map(item=>({...item,values:item.values||item.defaultValue?.split(',').map(value=>value.trim()).filter(Boolean)||[]}))}catch{return []}});
 const[msg,context]=message.useMessage();
 const[items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem('techzone_products'))||seed.map((x,i)=>({...x,sku:`TZ-${x.cat.toUpperCase()}-${1001+i}`,stock:12+i*7,active:true,featured:i<4}))}catch{return seed}});
 const request=(url,body)=>fetch(apiBaseUrl+url,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(response=>response.ok?response.json():Promise.reject());
 const persist=next=>{setItems(next);localStorage.setItem('techzone_products',JSON.stringify(next));request('/admin/products/',next).then(data=>setItems(data.results)).then(()=>msg.success('Đã lưu sản phẩm vào PostgreSQL')).catch(()=>msg.error('Không thể lưu sản phẩm vào máy chủ.'))};
 const persistCategories=next=>{setCategories(next);localStorage.setItem('techzone_categories',JSON.stringify(next));request('/admin/categories/',next).then(data=>setCategories(data.results.map(item=>item.name))).then(()=>msg.success('Đã lưu danh mục vào PostgreSQL')).catch(()=>msg.error('Không thể lưu danh mục vào máy chủ.'))};
 const persistAttributes=next=>{setAttributeDefinitions(next);localStorage.setItem('techzone_product_attributes',JSON.stringify(next));request('/admin/product-attributes/',next).then(data=>setAttributeDefinitions(data.results)).then(()=>msg.success('Đã lưu thuộc tính vào PostgreSQL')).catch(()=>msg.error('Không thể lưu thuộc tính vào máy chủ.'))};
 useEffect(()=>{Promise.all([fetch(apiBaseUrl+'/admin/categories/').then(response=>response.json()),fetch(apiBaseUrl+'/admin/product-attributes/').then(response=>response.json()),fetch(apiBaseUrl+'/admin/products/').then(response=>response.json())]).then(([categoryData,attributeData,productData])=>{if(categoryData.results?.length)setCategories(categoryData.results.map(item=>item.name));if(attributeData.results?.length)setAttributeDefinitions(attributeData.results);if(productData.results?.length)setItems(productData.results)}).catch(()=>msg.warning('Đang dùng dữ liệu cục bộ; chưa kết nối được API Django.'))},[msg]); useEffect(()=>{if(section!=='orders')return;setLoadingOrders(true);fetch(apiBaseUrl+'/admin/orders/').then(response=>response.json()).then(data=>setOrders(data.results||[])).finally(()=>setLoadingOrders(false))},[section]);
 useEffect(()=>{if(section!=='customers')return;setLoadingCustomers(true);fetch(apiBaseUrl+'/admin/customers/',{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setCustomers(data.results||[])).catch(()=>msg.error('Không thể tải dữ liệu khách hàng.')).finally(()=>setLoadingCustomers(false))},[section,msg]);
 const filtered=useMemo(()=>items.filter(x=>(category==='all'||x.cat===category)&&(x.name.toLowerCase().includes(query.toLowerCase())||(x.sku||'').toLowerCase().includes(query.toLowerCase()))),[items,query,category]);
 const edit=p=>{setEditing(p);setFormOpen(true)};
 const save=v=>{const attributes=(v.attributes||[]).map(a=>({name:a?.name?.trim(),value:Array.isArray(a?.value)?a.value.join(', '):a?.value?.trim()})).filter(a=>a.name&&a.value);const p={...editing,...v,attributes,id:editing?.id||Date.now(),price:Number(v.price),old:Number(v.old||v.price),stock:Number(v.stock||0),img:v.img||'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80',rate:editing?.rate||5,reviews:editing?.reviews||0};persist(editing?.id?items.map(x=>x.id===editing.id?p:x):[p,...items]);setFormOpen(false);setEditing(null)};
 const remove=p=>Modal.confirm({title:'Xóa sản phẩm?',content:`“${p.name}” sẽ bị xóa khỏi catalog.`,okText:'Xóa',cancelText:'Hủy',okButtonProps:{danger:true},onOk:()=>persist(items.filter(x=>x.id!==p.id))});
 const toggle=(p,key,value)=>persist(items.map(x=>x.id===p.id?{...x,[key]:value}:x));
 const columns=[
  {title:'SẢN PHẨM',dataIndex:'name',width:340,render:(_,p)=><Space size={12}><Image width={48} height={48} style={{objectFit:'cover',borderRadius:6}} src={p.img} fallback="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="/><Space direction="vertical" size={1}><Text strong>{p.name}</Text><Text type="secondary" className="sku">{p.sku||'Chưa có SKU'}</Text></Space></Space>},
  {title:'DANH MỤC',dataIndex:'cat',width:120,render:v=><Tag bordered={false}>{v}</Tag>},
  {title:'GIÁ BÁN',dataIndex:'price',width:145,render:(v,p)=><Space direction="vertical" size={0}><Text strong>{money(v)}</Text>{p.old>v&&<Text delete type="secondary" className="sku">{money(p.old)}</Text>}</Space>},
  {title:'TỒN KHO',dataIndex:'stock',width:120,sorter:(a,b)=>a.stock-b.stock,render:v=><Badge status={v===0?'error':v<10?'warning':'success'} text={`${v||0} sản phẩm`}/>},
  {title:'TRẠNG THÁI',dataIndex:'active',width:130,filters:[{text:'Đang bán',value:true},{text:'Đang ẩn',value:false}],onFilter:(v,r)=>r.active===v,render:(v,p)=><Button type="text" size="small" icon={v?<EyeOutlined/>:<EyeInvisibleOutlined/>} className={v?'selling':'hidden'} onClick={()=>toggle(p,'active',!v)}>{v?'Đang bán':'Đang ẩn'}</Button>},
  {title:'NỔI BẬT',dataIndex:'featured',width:90,align:'center',render:(v,p)=><Switch size="small" checked={v} onChange={n=>toggle(p,'featured',n)}/>},
  {title:'',key:'action',width:62,fixed:'right',render:(_,p)=><Dropdown trigger={['click']} menu={{items:[{key:'edit',icon:<EditOutlined/>,label:'Chỉnh sửa',onClick:()=>edit(p)},{type:'divider'},{key:'delete',danger:true,icon:<DeleteOutlined/>,label:'Xóa sản phẩm',onClick:()=>remove(p)}]}}><Button type="text" icon={<MoreOutlined/>}/></Dropdown>}
 ];
 const menu=[{key:'overview',icon:<AppstoreOutlined/>,label:'Tổng quan'},{key:'catalog',icon:<ShopOutlined/>,label:'Quản lý sản phẩm',children:[{key:'compatibility',label:'Quản lý tương thích'},{key:'products',label:'Sản phẩm'},{key:'categories',label:'Danh mục ngành hàng'},{key:'attributes',label:'Thuộc tính sản phẩm'}]},{key:'inventory',icon:<InboxOutlined/>,label:'Kho hàng'},{key:'promotions',icon:<TagsOutlined/>,label:'Khuyến mãi'},{key:'orders',icon:<ShoppingCartOutlined/>,label:'Quản lý đơn hàng'},{type:'divider'},{key:'customers',icon:<TeamOutlined/>,label:'Khách hàng'},{key:'employees',icon:<TeamOutlined/>,label:'Quản lý nhân viên'},{key:'data',icon:<InboxOutlined/>,label:'Quản lý dữ liệu'},{key:'settings',icon:<SettingOutlined/>,label:'Cài đặt'}];
 return <Layout className="ant-admin-layout">{context}<Sider collapsible collapsed={collapsed} trigger={null} width={238} className="ant-admin-sider"><a className="ant-brand" href="/"><span>TZ</span>{!collapsed&&<b>TECHZONE<small>ADMIN CENTER</small></b>}</a>{!collapsed&&<div className="store-select"><Text>KHÔNG GIAN LÀM VIỆC</Text><b>TechZone Store</b></div>}<Menu theme="dark" mode="inline" selectedKeys={[section]} onClick={({key})=>setSection(key)} items={menu}/><div className="sider-user"><Avatar style={{background:'#254366'}}>HV</Avatar>{!collapsed&&<><span><b>Hữu Vy</b><small>Quản trị viên</small></span><MoreOutlined/></>}</div></Sider>
  <Layout><Header className="ant-admin-header"><Button type="text" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(!collapsed)}/><Input variant="borderless" prefix={<SearchOutlined/>} placeholder="Tìm nhanh sản phẩm, đơn hàng..." className="header-search"/><Space className="header-right"><Button type="link" href="/" target="_blank">Xem cửa hàng <ArrowUpRight/></Button><Badge dot><Button type="text" shape="circle" icon={<BellOutlined/>}/></Badge></Space></Header>
   <Content className="ant-admin-content">{section==='overview'?<AdminOverview/>:section==='compatibility'?<CompatibilityManagement categories={categories} definitions={attributeDefinitions} products={items}/>:section==='employees'?<EmployeeManagement/>:section==='data'?<DataManagement/>:section==='categories'?<CategoryManagement categories={categories} products={items} save={persistCategories}/>:section==='attributes'?<AttributeManagement definitions={attributeDefinitions} products={items} save={persistAttributes}/>:section==='orders'?<OrderManagement orders={orders} loading={loadingOrders} onUpdated={order=>setOrders(current=>current.map(item=>item.id===order.id?order:item))}/>:section==='customers'?<CustomerManagement customers={customers} loading={loadingCustomers}/>:<><Breadcrumb items={[{title:'Catalog'},{title:'Sản phẩm'}]}/><div className="content-title"><div><Title level={2}>Quản lý sản phẩm</Title><Text type="secondary">Quản lý thông tin, giá bán và trạng thái sản phẩm trên cửa hàng.</Text></div><Button type="primary" icon={<PlusOutlined/>} size="large" onClick={()=>{setEditing(null);setFormOpen(true)}}>Thêm sản phẩm</Button></div>
    <Row gutter={[14,14]} className="stat-row"><Stat title="Tổng sản phẩm" value={items.length} icon={<ShopOutlined/>}/><Stat title="Đang hiển thị" value={items.filter(x=>x.active).length} icon={<EyeOutlined/>} color="green"/><Stat title="Sắp hết hàng" value={items.filter(x=>x.stock>0&&x.stock<10).length} icon={<WarningOutlined/>} color="orange"/><Stat title="Hết hàng" value={items.filter(x=>!x.stock).length} icon={<InboxOutlined/>} color="red"/></Row>
    <Card className="catalog-card" styles={{body:{padding:0}}}><div className="catalog-tools"><Input allowClear prefix={<SearchOutlined/>} placeholder="Tìm theo tên hoặc mã SKU..." value={query} onChange={e=>setQuery(e.target.value)} className="catalog-search"/><Select value={category} onChange={setCategory} options={[{label:'Tất cả danh mục',value:'all'},...categories.map(x=>({label:x,value:x}))]}/><Text type="secondary">{filtered.length} sản phẩm</Text></div><Table rowKey="id" columns={columns} dataSource={filtered} scroll={{x:1050}} pagination={{pageSize:8,showSizeChanger:false,showTotal:n=>`Tổng ${n} sản phẩm`}}/></Card>
   </>}</Content></Layout><ProductDrawer categories={categories} definitions={attributeDefinitions} open={formOpen} data={editing} close={()=>{setFormOpen(false);setEditing(null)}} save={save}/></Layout>
}
function OrderManagement({orders,loading,onUpdated}){
 const {message:orderMessage}=AntApp.useApp();
 const [saving,setSaving]=useState({});
 const [employees,setEmployees]=useState([]),[loadingEmployees,setLoadingEmployees]=useState(true);
 useEffect(()=>{fetch(`${apiBaseUrl}/admin/employees/`,{credentials:'include'}).then(response=>response.ok?response.json():Promise.reject()).then(data=>setEmployees(data.results)).catch(()=>orderMessage.error('Không thể tải nhân viên.')).finally(()=>setLoadingEmployees(false))},[orderMessage]);
 const statuses=[{value:'PENDING_PAYMENT',label:'Chờ thanh toán',color:'default'},{value:'CONFIRMED',label:'Đã xác nhận',color:'cyan'},{value:'PACKING',label:'Đang đóng gói',color:'processing'},{value:'DELIVERING',label:'Đang giao',color:'warning'},{value:'DELIVERED',label:'Đã giao',color:'success'},{value:'CANCELLED',label:'Đã hủy',color:'error'}];
 const statusTag=value=>{const status=statuses.find(item=>item.value===value);return <Tag color={status?.color||'default'} style={{marginInlineEnd:0}}>{status?.label||value}</Tag>};
 const update=async(id,body)=>{
  if(saving[id])return;
  setSaving(current=>({...current,[id]:true}));
  try{
   const response=await fetch(`${apiBaseUrl}/admin/orders/${id}/`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
   const data=await response.json();
   if(!response.ok)throw new Error(data.message);
   if(!data.order)throw new Error();
   onUpdated(data.order);
   orderMessage.success('Đã cập nhật đơn hàng.');
  }catch(error){orderMessage.error(error.message||'Không thể cập nhật đơn hàng. Vui lòng thử lại.')}
  finally{setSaving(current=>({...current,[id]:false}))}
 };
 const columns=[{title:'MÃ ĐƠN',dataIndex:'code',render:value=><Text strong>#{value}</Text>},{title:'KHÁCH HÀNG',dataIndex:'recipient',render:value=><Space direction="vertical" size={0}><Text>{value.name}</Text><Text type="secondary">{value.phone}</Text></Space>},{title:'TỔNG TIỀN',dataIndex:'totals',render:value=>money(value.grand_total)},{title:'TRẠNG THÁI',dataIndex:'status',render:(value,order)=><Select aria-label={`Trạng thái đơn hàng ${order.code}`} value={value} style={{width:180}} loading={!!saving[order.id]} disabled={!!saving[order.id]||value==='CANCELLED'} options={statuses.map((item,index)=>({...item,disabled:index!==statuses.findIndex(status=>status.value===value)+1||value==='CANCELLED'}))} labelRender={({value:selected})=>statusTag(selected)} optionRender={option=>statusTag(option.value)} onChange={status=>{if(status!==value)update(order.id,{status})}}/>},{title:'NGƯỜI XỬ LÝ',dataIndex:'handler',render:(value,order)=><Select aria-label={`Người xử lý ${order.code}`} style={{width:220}} value={value?.id} placeholder="Chưa phân công" allowClear showSearch optionFilterProp="label" loading={loadingEmployees} disabled={loadingEmployees||!!saving[order.id]} options={[...employees.map(employee=>({value:employee.user_id,label:employee.full_name,disabled:!employee.active})),...(value&&!employees.some(employee=>employee.user_id===value.id)?[{value:value.id,label:value.name,disabled:true}]:[])]} onChange={id=>update(order.id,{handler_id:id??null})}/>},{title:'NGÀY ĐẶT',dataIndex:'created_at',render:value=>new Date(value).toLocaleString('vi-VN')}];
 return <><Breadcrumb items={[{title:'Quản lý đơn hàng'}]}/><div className="content-title"><div><Title level={2}>Quản lý đơn hàng</Title><Text type="secondary">Theo dõi trạng thái, người xử lý và sản phẩm trong từng đơn.</Text></div></div><Card className="catalog-card" styles={{body:{padding:0}}}><Table rowKey="id" columns={columns} dataSource={orders} loading={loading} expandable={{expandedRowRender:order=><List bordered size="small" dataSource={order.items} renderItem={item=><List.Item actions={[<Text key="quantity">Số lượng: {item.quantity}</Text>,<Text strong key="total">{money(item.total)}</Text>]}><List.Item.Meta avatar={<Avatar shape="square" src={item.image}/>} title={item.name} description={`SKU: ${item.sku} • ${money(item.price)}/sản phẩm`}/></List.Item>}/>}} pagination={{pageSize:8}}/></Card></>;
}function AttributeManagement({definitions,products,save}){
 const[name,setName]=useState(''),[valuesInput,setValuesInput]=useState('');
 const add=()=>{const value=name.trim();if(!value||definitions.some(item=>item.name.toLowerCase()===value.toLowerCase()))return;const values=valuesInput.split(',').map(item=>item.trim()).filter(Boolean);save([...definitions,{id:crypto.randomUUID(),name:value,values}]);setName('');setValuesInput('')};
 const used=item=>products.some(product=>(product.attributes||[]).some(attribute=>attribute.name===item.name));
 const columns=[{title:'THUỘC TÍNH',dataIndex:'name',width:420,render:value=><Text strong>{value}</Text>},{title:'GIÁ TRỊ CHO PHÉP',dataIndex:'values',render:values=>values?.join(', ')||'—'},{title:'ĐANG GẮN',key:'used',render:(_,item)=>products.filter(product=>(product.attributes||[]).some(attribute=>attribute.name===item.name)).length},{title:'',key:'action',width:100,render:(_,item)=><Button danger type="text" disabled={used(item)} onClick={()=>save(definitions.filter(value=>value.id!==item.id))}>Xóa</Button>}];
 return <><Breadcrumb items={[{title:'Quản lý sản phẩm'},{title:'Thuộc tính sản phẩm'}]}/><div className="content-title"><div><Title level={2}>Thuộc tính sản phẩm</Title><Text type="secondary">Khai báo thuộc tính để gắn nhanh khi tạo hoặc chỉnh sửa sản phẩm.</Text></div></div><Card className="catalog-card" styles={{body:{padding:0}}}><div className="catalog-tools"><Input value={name} onChange={event=>setName(event.target.value)} placeholder="Tên thuộc tính, ví dụ: Dung lượng" className="catalog-search"/><Input value={valuesInput} onChange={event=>setValuesInput(event.target.value)} onPressEnter={add} placeholder="Giá trị, ví dụ: 8GB, 16GB" style={{width:180}}/><Button type="primary" icon={<PlusOutlined/>} onClick={add}>Thêm thuộc tính</Button></div><Table rowKey="id" columns={columns} dataSource={definitions} pagination={false}/></Card></>;
}function CategoryManagement({categories,products,save}){
 const[name,setName]=useState('');
 const add=()=>{const value=name.trim();if(!value)return;if(categories.some(category=>category.toLowerCase()===value.toLowerCase()))return;save([...categories,value]);setName('')};
 const remove=category=>{if(products.some(product=>product.cat===category))return;save(categories.filter(item=>item!==category))};
 const columns=[{title:'DANH MỤC NGÀNH HÀNG',dataIndex:'name',width:420,render:value=><Text strong>{value}</Text>},{title:'SẢN PHẨM ĐANG GẮN',key:'products',render:(_,record)=>products.filter(product=>product.cat===record.name).length},{title:'',key:'actions',width:100,render:(_,record)=><Button danger type="text" disabled={products.some(product=>product.cat===record.name)} onClick={()=>remove(record.name)}>Xóa</Button>}];
 return <><Breadcrumb items={[{title:'Quản lý sản phẩm'},{title:'Danh mục ngành hàng'}]}/><div className="content-title"><div><Title level={2}>Danh mục ngành hàng</Title><Text type="secondary">Tạo danh mục và gắn danh mục vào từng sản phẩm.</Text></div></div><Card className="catalog-card" styles={{body:{padding:0}}}><div className="catalog-tools"><Input value={name} onChange={event=>setName(event.target.value)} onPressEnter={add} placeholder="Ví dụ: Laptop gaming" className="catalog-search"/><Button type="primary" icon={<PlusOutlined/>} onClick={add}>Thêm danh mục</Button></div><Table rowKey="name" columns={columns} dataSource={categories.map(name=>({name}))} pagination={false}/></Card></>;
}function CustomerManagement({customers,loading}){
 const[query,setQuery]=useState('');
 const filtered=useMemo(()=>customers.filter(customer=>`${customer.full_name} ${customer.email} ${customer.phone}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);
 const columns=[{title:'KHÁCH HÀNG',dataIndex:'full_name',render:(value,customer)=><Space><Avatar style={{background:'#1768f2'}}>{value?.trim()?.[0]?.toUpperCase()}</Avatar><Space direction="vertical" size={0}><Text strong>{value}</Text><Text type="secondary">{customer.email}</Text></Space></Space>},{title:'SỐ ĐIỆN THOẠI',dataIndex:'phone',width:180},{title:'NGÀY ĐĂNG KÝ',dataIndex:'created_at',width:190,render:value=>new Date(value).toLocaleString('vi-VN')}];
 return <><Breadcrumb items={[{title:'Khách hàng'}]}/><div className="content-title"><div><Title level={2}>Khách hàng</Title><Text type="secondary">Danh sách tài khoản đã đăng ký và được lưu trong PostgreSQL.</Text></div></div><Card className="catalog-card" styles={{body:{padding:0}}}><div className="catalog-tools"><Input allowClear prefix={<SearchOutlined/>} placeholder="Tìm theo tên, email hoặc số điện thoại..." value={query} onChange={event=>setQuery(event.target.value)} className="catalog-search"/><Text type="secondary">{filtered.length} khách hàng</Text></div><Table rowKey="id" columns={columns} dataSource={filtered} loading={loading} pagination={{pageSize:8,showSizeChanger:false,showTotal:total=>`Tổng ${total} khách hàng`}}/></Card></>;
}function Stat({title,value,icon,color=''}){return <Col xs={12} lg={6}><Card className="stat-card"><Space><Avatar size={46} className={`stat-icon ${color}`} icon={icon}/><Statistic title={title} value={value}/></Space></Card></Col>}
function AttributeValueInput({definitions,form,fieldIndex}){
 const attributeName=Form.useWatch(['attributes',fieldIndex,'name'],form);
 const definition=definitions.find(item=>item.name===attributeName);
 if(definition?.values?.length)return <Select style={{width:320,minWidth:320}} mode="multiple" placeholder="Chọn một hoặc nhiều giá trị" options={definition.values.map(value=>({label:value,value}))}/>;
 return <Input placeholder="Giá trị"/>;
}function ProductDrawer({categories,definitions,open,data,close,save}){
 const[form]=Form.useForm();
 return <Drawer title={<Space direction="vertical" size={0}><Text type="secondary" className="drawer-eyebrow">{data?'CHỈNH SỬA':'TẠO MỚI'}</Text><Title level={4} style={{margin:0}}>{data?'Cập nhật sản phẩm':'Thêm sản phẩm'}</Title></Space>} width={620} open={open} onClose={close} destroyOnHidden afterOpenChange={v=>v&&form.setFieldsValue(data?{...data,attributes:data.attributes?.length?data.attributes:[{name:'',value:''}]}:blank)} extra={<Button type="primary" icon={<SaveOutlined/>} onClick={()=>save(form.getFieldsValue(true))}>Lưu</Button>}>
  <Form form={form} layout="vertical" onFinish={save} initialValues={blank}>
   <Form.Item label="Tên sản phẩm" name="name" rules={[{required:true,message:'Nhập tên sản phẩm'}]}><Input placeholder="AMD Ryzen 7 7800X3D"/></Form.Item>
   <Row gutter={12}><Col span={12}><Form.Item label="Mã SKU" name="sku" rules={[{required:true,message:'Nhập mã SKU'}]}><Input placeholder="TZ-CPU-1001"/></Form.Item></Col><Col span={12}><Form.Item label="Thương hiệu" name="brand"><Input placeholder="AMD"/></Form.Item></Col></Row>
   <Row gutter={12}><Col span={12}><Form.Item label="Danh mục" name="cat"><Select options={categories.map(x=>({label:x,value:x}))}/></Form.Item></Col><Col span={12}><Form.Item label="Nhãn sản phẩm" name="badge"><Input placeholder="MỚI"/></Form.Item></Col></Row>
      <Card size="small" title="Thông số kỹ thuật" className="attribute-card"><Form.Item label="Gắn thuộc tính đã tạo"><Select mode="multiple" placeholder="Chọn thuộc tính cần gắn" options={definitions.map(item=>({label:`${item.name}${item.unit?` (${item.unit})`:''}`,value:item.id}))} onChange={ids=>form.setFieldValue('attributes',ids.map(id=>{const item=definitions.find(value=>value.id===id);return {name:item.name,value:[],unit:item.unit||''}}))}/></Form.Item><Form.List name="attributes">{(fields,{add,remove})=><><Space direction="vertical" size={8} style={{width:'100%'}}>{fields.map(({key,name,...rest})=><Row gutter={8} key={key} wrap={false}><Col flex="0 0 180px"><Form.Item {...rest} name={[name,'name']} rules={[{required:true,message:'Nhập tên'}]} noStyle><Input placeholder="Tên thuộc tính"/></Form.Item></Col><Col flex="0 0 320px" style={{width:320,minWidth:320,flex:'0 0 320px'}}><Form.Item {...rest} name={[name,'value']} rules={[{required:true,message:'Chọn hoặc nhập giá trị'}]} noStyle><AttributeValueInput definitions={definitions} form={form} fieldIndex={name}/></Form.Item></Col><Col flex="0 0 34px"><Button danger type="text" icon={<DeleteOutlined/>} aria-label="Xóa thuộc tính" onClick={()=>remove(name)}/></Col></Row>)}</Space><Button type="dashed" icon={<PlusOutlined/>} block onClick={()=>add({name:'',value:''})} style={{marginTop:10}}>Thêm giá trị thuộc tính</Button></>}</Form.List></Card>
   <Row gutter={12}><Col span={12}><Form.Item label="Giá bán" name="price" rules={[{required:true,message:'Nhập giá bán'}]}><InputNumber min={0} style={{width:'100%'}} addonAfter="₫"/></Form.Item></Col><Col span={12}><Form.Item label="Giá gốc" name="old"><InputNumber min={0} style={{width:'100%'}} addonAfter="₫"/></Form.Item></Col></Row>
   <Form.Item label="Số lượng tồn kho" name="stock"><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item label="URL hình ảnh" name="img"><Input placeholder="https://..."/></Form.Item><Form.Item label="Mô tả ngắn" name="description"><Input.TextArea rows={3} placeholder="Thông tin nổi bật hiển thị cạnh sản phẩm..."/></Form.Item><Form.Item label="Thông tin sản phẩm" name="productInfo"><Input.TextArea rows={6} placeholder="Mô tả chi tiết, công nghệ nổi bật, đối tượng sử dụng..." showCount maxLength={5000}/></Form.Item>
   <Card size="small" style={{marginTop:16}}><Form.Item name="active" valuePropName="checked" label="Hiển thị trên cửa hàng"><Switch checkedChildren="Đang bán" unCheckedChildren="Đang ẩn"/></Form.Item><Form.Item name="featured" valuePropName="checked" label="Sản phẩm nổi bật" style={{marginBottom:0}}><Switch/></Form.Item></Card>
  </Form>
 </Drawer>
}
function ArrowUpRight(){return <span style={{fontSize:12}}>↗</span>}
