import React,{useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,ShoppingBag,Zap,Monitor,Cpu,Flame} from 'lucide-react';
import './home-promotions.css';
const money=value=>Number(value).toLocaleString('vi-VN')+' ₫';
const pcProduct=product=>/^(pc|pc gaming|pc workstation|máy tính bộ|máy bộ)$/i.test(product.cat||'');
function ProductRail({children,label}){
 const rail=useRef(null);
 const scroll=direction=>rail.current?.scrollBy({left:direction*rail.current.clientWidth*.8,behavior:'smooth'});
 return <div className="promo-rail-wrap"><button className="promo-arrow promo-prev" aria-label={`${label}: xem trước`} onClick={()=>scroll(-1)}><ChevronLeft/></button><div className="promo-rail" ref={rail}>{children}</div><button className="promo-arrow promo-next" aria-label={`${label}: xem tiếp`} onClick={()=>scroll(1)}><ChevronRight/></button></div>;
}
function ProductCard({product,add,pc,upcoming}){
 const discount=product.old>product.price?Math.round((1-product.price/product.old)*100):0;
 const unavailable=product.stock<=0||upcoming;
 return <article className={`promo-product ${pc?'promo-pc':''}`}><a className="promo-picture" href={`/product/${product.id}`}><img src={product.img} alt={product.name} loading="lazy"/>{product.flashSaleId&&<span className="flash-sale-badge"><Zap/> Flash sale</span>}{!pc&&discount>0&&<span className="promo-saving">TIẾT KIỆM<strong>{money(product.old-product.price)}</strong><Zap/></span>}</a><a className="promo-name" href={`/product/${product.id}`}>{product.name}</a>{pc&&<div className="promo-specs">{product.attributes?.length?product.attributes.slice(0,4).map((item,index)=><span key={index}><Cpu/>{item.name}: {Array.isArray(item.value)?item.value.join(', '):item.value} {item.unit||''}</span>):<span><Monitor/>Xem cấu hình chi tiết sản phẩm</span>}</div>}<div className="promo-price">{money(product.price)}</div><div className="promo-old">{discount>0&&<><del>{money(product.old)}</del><span>-{discount}%</span></>}</div><div className="promo-actions"><span className={unavailable?'promo-unavailable':''}>{upcoming?'Sắp mở bán':product.stock<=0?'Tạm hết hàng':Number.isFinite(product.stock)?`Còn ${product.stock} sản phẩm`:'Còn hàng'}</span><button disabled={unavailable} onClick={()=>add(product)} aria-label={`Thêm ${product.name} vào giỏ`}><ShoppingBag/></button></div>{!pc&&<div className="promo-sale-strip"><Flame/>{Number.isFinite(product.sold)?`Đã bán ${product.sold}`:'Ưu đãi đang chờ bạn'}</div>}</article>;
}
export default function HomePromotions({products,add,openBuilder}){
 const [deal,setDeal]=useState('current'),[family,setFamily]=useState('all'),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 const [sales,setSales]=useState([]),[saleError,setSaleError]=useState(false);
 useEffect(()=>{let disposed=false;const load=()=>fetch(`${import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api'}/flash-sales/`).then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(!disposed){setSales(data.results);setSaleError(false)}}).catch(()=>{if(!disposed)setSaleError(true)});load();const timer=setInterval(load,15000);return()=>{disposed=true;clearInterval(timer)}},[]);
 const active=products.filter(p=>p.active!==false);
 const deals=sales.filter(s=>s.active&&s.remaining>0&&Date.parse(s.ends_at)>now&&(deal==='upcoming'?Date.parse(s.starts_at)>now:Date.parse(s.starts_at)<=now)).map(s=>({...s.product,flashSaleId:s.id,saleStart:s.starts_at,saleEnd:s.ends_at,sold:s.sold,stock:Math.min(s.remaining,Number.isFinite(s.product.stock)?s.product.stock:s.remaining)}));
 const deadline=Math.min(...deals.map(p=>Date.parse(deal==='upcoming'?p.saleStart:p.saleEnd)).filter(Number.isFinite));
 const seconds=Math.max(0,Math.floor((deadline-now)/1000));
 const countdown=Number.isFinite(deadline)?[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(v=>String(v).padStart(2,'0')):null;
 const pcs=active.filter(pcProduct).filter(p=>family==='all'||new RegExp(family,'i').test(`${p.name} ${(p.attributes||[]).map(a=>`${a.name} ${a.value}`).join(' ')}`)).sort((a,b)=>(b.sold||0)-(a.sold||0));
 return <div className="home-promotions"><section className="flash-block" aria-label="Flash Sale"><div className="flash-heading"><h2>FLASH SALE <Zap fill="currentColor"/></h2>{countdown&&<div className="flash-countdown" aria-label={`Còn ${countdown.join(':')}`}><small>{deal==='upcoming'?'Bắt đầu sau':'Kết thúc sau'}</small>{countdown.map((value,index)=><React.Fragment key={index}>{index>0&&<span>:</span>}<b>{value}</b></React.Fragment>)}</div>}<div className="flash-tabs">{[['current','Deal đang diễn ra'],['upcoming','Deal sắp diễn ra']].map(([value,label])=><button key={value} aria-pressed={deal===value} className={deal===value?'active':''} onClick={()=>setDeal(value)}>{label}</button>)}</div></div>{deals.length?<ProductRail label="Flash Sale">{deals.map(p=><ProductCard key={p.id} product={p} add={add} upcoming={deal==='upcoming'}/>)}</ProductRail>:<div className="promo-empty">{deal==='upcoming'?'Chưa có chương trình sắp diễn ra.':'Các ưu đãi mới sẽ sớm được cập nhật.'}</div>}<a className="flash-all" href="/collections/all">MUA SẮM TOÀN BỘ SẢN PHẨM <ChevronRight/></a></section><section className="pc-block" aria-label="PC bán chạy"><div className="pc-heading"><h2>PC bán chạy</h2><span className="pc-subtitle"><Monitor/> Cấu hình cho mọi nhu cầu</span><div className="pc-tabs">{[['all','Tất cả'],['i3','PC i3'],['i5','PC i5'],['i7','PC i7'],['i9','PC i9'],['ryzen 3','PC R3'],['ryzen 5','PC R5'],['ryzen 9','PC R9']].map(([value,label])=><button key={value} aria-pressed={family===value} className={family===value?'active':''} onClick={()=>setFamily(value)}>{label}</button>)}</div></div>{pcs.length?<ProductRail label="PC bán chạy">{pcs.map(p=><ProductCard key={p.id} product={p} add={add} pc/>)}</ProductRail>:<div className="pc-empty"><Monitor/><h3>{family==='all'?'Các bộ PC đang được cập nhật':'Chưa có PC thuộc nhóm này'}</h3><p>Tự chọn linh kiện phù hợp và kiểm tra tương thích với PC Builder.</p><button onClick={openBuilder}>Xây dựng PC của bạn <ChevronRight/></button></div>}</section></div>;
}
