import React,{useEffect,useState} from 'react';
import {checkCompatibility} from './compatibility.mjs';
const categories=['CPU','Mainboard','RAM','VGA','SSD','Nguồn','Case'];
const money=value=>Number(value).toLocaleString('vi-VN')+'₫';
export default function PcBuilder({close,add,products}){
 const [selected,setSelected]=useState([]),[rules,setRules]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(`${import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api'}/compatibility-rules/`,{signal:controller.signal}).then(response=>response.ok?response.json():Promise.reject()).then(data=>setRules(data.results)).catch(e=>{if(e.name!=='AbortError')setError('Không tải được ràng buộc tương thích. Hãy mở lại bộ build để thử lại.')}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
 const checks=checkCompatibility(selected,rules),issues=checks.filter(check=>check.status!=='pass');
 const blocked=loading||!!error||!!issues.length||!selected.length;
 return <div className="modal-wrap"><div className="builder"><div className="builder-top"><div><h2>Xây dựng cấu hình của bạn</h2><p>Chọn linh kiện và kiểm tra các ràng buộc tương thích.</p></div><button aria-label="Đóng" onClick={close}>✕</button></div><div className="builder-content"><div className="slots">{categories.map((category,index)=>{const current=selected.find(p=>p.cat===category);return <div className={`builder-component ${current?'filled':''}`} key={category}><span>{index+1}</span><b>{category}</b><select aria-label={`Chọn ${category}`} value={current?.id??''} onChange={event=>{const product=products.find(p=>String(p.id)===event.target.value&&p.cat===category);setSelected(items=>[...items.filter(p=>p.cat!==category),...(product?[product]:[])])}}><option value="">Chọn linh kiện</option>{products.filter(p=>p.cat===category&&p.active!==false&&p.stock!==0).map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></div>})}</div><aside><div className={`compat ${issues.length||error?'compat-warning':''}`}><b>{loading?'Đang kiểm tra…':error?'Chưa kiểm tra được':issues.length?'Cần kiểm tra cấu hình':checks.length?'Đạt các ràng buộc đã kiểm tra':'Chưa có ràng buộc áp dụng'}</b>{error&&<p role="alert">{error}</p>}{!loading&&!error&&!checks.length&&<p>Chọn linh kiện có ràng buộc để kiểm tra. Kết quả chỉ bao gồm các quy tắc đã cấu hình.</p>}{checks.map((check,index)=><p key={index}><strong>{check.status==='pass'?'✓':'!'} {check.rule}</strong><br/>{check.pair}<br/>{check.message}</p>)}</div><h3>Tóm tắt cấu hình</h3><div className="sum"><span>{selected.length}/7 linh kiện</span><b>{money(selected.reduce((sum,p)=>sum+p.price,0))}</b></div><button className="primary" disabled={blocked} onClick={()=>{if(!blocked)selected.forEach(add)}}>THÊM CẤU HÌNH VÀO GIỎ</button></aside></div></div></div>;
}
