# Generated by Django 5.2.17 on 2026-09-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('province_code', models.CharField(max_length=20)),
                ('province_name', models.CharField(max_length=150)),
                ('ward_code', models.CharField(max_length=20)),
                ('ward_name', models.CharField(max_length=150)),
                ('detail', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.customer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
