# Generated by Django 5.2.17 on 2026-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
