# Generated by Django 5.2.17 on 2026-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_knowledgedocument_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE', 'Nhân viên kho'), ('ORDER_PROCESSOR', 'Nhân viên xử lý')], default='ORDER_PROCESSOR', max_length=24),
        ),
    ]
