# Generated by Django 5.2.17 on 2026-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_category', models.CharField(max_length=100)),
                ('source_attribute', models.CharField(max_length=100)),
                ('target_category', models.CharField(max_length=100)),
                ('target_attribute', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
